language: scala
scala:
  - 2.13.8
jdk:
  - oraclejdk8
  - oraclejdk11

# FIXME: tests are disabled due to Fongo incompatibility with Scala Mongo driver.
script: "sbt assembly"
#script: "sbt clean coverage test"
#after_success: "sbt coveralls"
